baseURL: "http://hugo-quickstart-template.netlify.com"
languageCode: "en-us"
title: "Netlify + Hugo Quickstart"
theme: "netlify-basic"

params:
  colors:
    primary: "#CBE2CE"     # most relevant
    secondary: "#FCEDF3"
    darkgreen: "#004225"
    burgundy: "#722F37"
    taupe: "#98817B"


languages:
  en:
    languageName: "English"
    weight: 1
  es:
    languageName: "Español"
    weight: 2
  ua:
    languageName: "Українська"
    weight: 3
