backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/en/_index.md"
        label: "Homepage EN"
        name: "homepage_en"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/es/_index.md"
        label: "Homepage ES"
        name: "homepage_es"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/uk/_index.md"
        label: "Homepage UK"
        name: "homepage_uk"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "travel"
    label: "Travel & Accommodation"
    folder: "content/en/travel"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
